Repository Laravel-Backpack/FileManager, pull requests merged in 2023-07, with the labels that each got.

#26 v6
  composer.json
  resources/assets/css/elfinder.backpack.theme.css
  resources/views/ckeditor4.blade.php
  resources/views/common_scripts.blade.php
  resources/views/common_styles.blade.php
  resources/views/elfinder.blade.php
  resources/views/filepicker.blade.php
  resources/views/standalonepopup.blade.php
  resources/views/tinymce.blade.php
  resources/views/tinymce4.blade.php
  resources/views/tinymce5.blade.php
  src/Console/Commands/Install.php
  src/FileManagerServiceProvider.php
Labels: Priority: MUST

#29 fix: replace `add-sidebar-content`
  src/Console/Commands/Install.php
Labels: bug

#31 Switch from using .zip to .tar.gz for basset archives
  resources/views/common_scripts.blade.php
  resources/views/common_styles.blade.php
Labels: Priority: SHOULD
